config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
              controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end
  
  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: [:index] do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: :index
  end
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/admin/gists_controller.rb
class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.all
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_test_passage, only: :create

  def create
    result = GistQuestionService.new(@test_passage.current_question).call

    flash_options = if result.success?
      
      current_user.gists.create!(url: result.gist_url,
                   user: @test_passage.user,
                   question: @test_passage.current_question)
      { notice: t('.success', url: result.gist_url) }
    else
      { alert: t('.failure')}
    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:test_passage])
  end
end

app/views/admin/gists/_gist.html.erb
<tr>
  <td><%= link_to truncate("#{gist.question.body}", length: 25), admin_question_path(gist.question) %></td>
  <td><%= gist_url(gist.url) %></td>
  <td><%= gist.user.email %>      
</tr>

app/views/admin/gists/index.html.erb
<h3><%= t('.header') %></h3>
<table>
  <tr>
    <th><%= t('.question') %></th>
    <th><%= t('.gist_url') %></th>
    <th><%= t('.user') %></th>
  </tr>
  <%= render @gists %>
</table>
<%= link_to t(".root"), admin_tests_path %>