config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
              controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end
  
  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: [:index] do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: :index
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def completed?
    current_question.nil?
  end
  
  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def success_calculation
    (correct_questions.to_f * 100 / test.questions.count).round
  end

  def question_number
    test.questions.index(current_question) + 1
  end

  def questions_count
    test.questions.count
  end

  def test_passed?
    success_calculation >= SUCCESS_RATE 
  end
  
  private
  
  def set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end
  
  def correct_answers
    current_question.answers.correct
  end
  
  def next_question
    if current_question
      test.questions.order(:id).where('id > ?', current_question.id).first
    else
      test.questions.first
    end
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else 
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t(".header", title: @test_passage.test.title) %></h1>

<% if @test_passage.test_passed? %>
  <p style="color: green"><%= t(".passed") %></p>
<% else %>
  <p style="color: red"><%= t(".failed") %></p>
<% end %>
<p>

<%= link_to  t(".move_back"), tests_path %>

app/views/test_passages/show.html.erb
<div class="fw-normal">
  <h1><%= t('.header')%> <%= @test_passage.test.title %>Test</h1>

  <p>
    <b><%= @test_passage.current_question.body %></b>
  </p>

  <%= form_with url: test_passage_path(@test_passage), local: false, data: { turbo: false }, method: :put do |form| %>
    <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
      <p>  
        <%= b.check_box id: "answer_ids_#{b.object.id}" %>
        <%= b.label %>
      </p>
    <% end %>

    
    <p><%= form.submit t(".next") %></p>

    <p><%= t(".question_number") %>: <%= @test_passage.question_number %></p>
    <p><%= t(".question_count") %>: <%= @test_passage.questions_count %>
  <% end %>
  <p><%= link_to t(".gist_question"), gists_path(test_passage: @test_passage), data: { turbo_method: :post } %></p>
</div>