config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
              controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end
  
  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: [:index] do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: :index
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validates :correct, inclusion: [true, false]
  validate :check_answers_count, on: :create

  scope :correct, -> { where(correct: true) }
  
  private

  def check_answers_count
    errors.add(:base, "the question must have from 1 to 4 answers") if question.answers.count >= 4 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy_tests_by_level, -> { where(level: 0..1) }
  scope :medium_tests_by_level, -> { where(level: 2..4) }
  scope :hard_tests_by_level, -> { where(level: 5..Float::INFINITY) }

  scope :by_category, ->(category) { 
    joins(:category)
      .where(categories: { title: category }) 
      .order(title: :desc)
  }

  def self.titles_by_category(category)
    by_category(category).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def completed?
    current_question.nil?
  end
  
  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def success_calculation
    (correct_questions.to_f * 100 / test.questions.count).round
  end

  def question_number
    test.questions.index(current_question) + 1
  end

  def questions_count
    test.questions.count
  end

  def test_passed?
    success_calculation >= SUCCESS_RATE 
  end
  
  private
  
  def set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end
  
  def correct_answers
    current_question.answers.correct
  end
  
  def next_question
    if current_question
      test.questions.order(:id).where('id > ?', current_question.id).first
    else
      test.questions.first
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable,
         :validatable,
         :confirmable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :tests_author, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :email, uniqueness: true

  def passed_tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  layout 'admin'

  before_action :authenticate_user!
  before_action :admin_required!

  private

  def admin_required!
    redirect_to root_path, alert: 'You are not authtorized to view this page.' unless current_user.is_a?(Admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def default_url_options
    { locale: (I18n.locale unless I18n.locale == I18n.default_locale ) }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  def after_sign_in_path_for(user)
    user.is_a?(Admin) ? admin_tests_path : tests_path
  end

  def set_locale
    I18n.locale = I18n.locale_available?(params[:lang]) ? params[:lang] : I18n.default_locale
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_test_passage, only: :create

  def create
    result = GistQuestionService.new(@test_passage.current_question).call

    flash_options = if result.success?
      
      current_user.gists.create!(url: result.gist_url,
                   user: @test_passage.user,
                   question: @test_passage.current_question)
      { notice: t('.success', url: result.gist_url) }
    else
      { alert: t('.failure')}
    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:test_passage])
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else 
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_test, only: %i[start]

  rescue_from ActiveRecord::RecordNotFound, with: :record_test_not_found

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end
  
  def record_test_not_found
    render plain: "Test Not Found"
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'Github', "https://github.com/#{author}/#{repo}", :target => "_blank", :rel => "noopener noreferrer"
  end

  def gist_url(gist_url)
    link_to "#{URI(gist_url).path}", "#{gist_url}", :target => "_blank", :rel => "noopener noreferrer"
  end

  def flash_message
    content_tag :div, class: "flash-messages" do
      flash.map do |key, value| 
        content_tag :div, class: "alert alert-dismissable alert-#{key}" do 
          content_tag(:span, '&times;'.html_safe, class: :close, 'data-dismiss' => 'alert') + value
        end
      end.join().html_safe
    end
  end

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header
    test_title = @question.test.title
    @question.new_record? ? "<#{test_title}>" : "<#{test_title}>"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<div class="navbar navbar-light bg-primary p-4">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <%= link_to t(".logo"), root_path, class: 'navbar-brand text-light' %>
      <span class="text-light"><%= t(".admin_panel") %>
    </li>
  </ul>
  <div class="text-light">
    <%= t(".greeting") %>, <b class="nav-admin user-email"><%= current_user.email %></b>
    <%= link_to t(".logout"), destroy_user_session_path, data: {turbo_method: :delete}, class: "text-warning" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="fw-normal">
  <hr class="solid">
  <p>Andrey Reznichenko</p>
  <p><%= current_year %></p>
  <p><%= github_url('Ehxdex', 'TestGuru') %></p>
  <p><%= link_to "Учебный проект в онлайн-школе Thinknetica", 'https://thinknetica.com', :target => "_blank", :rel => "noopener noreferrer" %></p>
  </div>
</footer>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Admin Panel | TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'admin/nav' %>
    <%= render 'shared/flash' %>

    <%= yield %>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width", initial-scale=1, shrink-to-fit="no">
    
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    <div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.errors.present? %>
  <div>
    <h2><%= t(".header", count: resource.errors.count) %></h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="<%= flash_class(key) %>">
    <%= content_tag :p, message.html_safe, class: "flash #{key}" %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light p-4">
  <%= link_to t(".logo"), root_path, class: 'navbar-brand' %> 
  <% if current_user.is_a?(Admin) %>
    <%= link_to t(".admin_panel"), admin_tests_path %>
  <% end %>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <p class="nav user">
      <%= t(".greeting") %>, <b><%= current_user.email %><b>
      <%= link_to t(".logout"), destroy_user_session_path, data: {turbo_method: :delete} %>
    <% else %>
      <%= link_to t(".login"), new_session_path(resource_name) %> |
      <%= link_to t(".signup"), new_registration_path(resource_name) %>
    <% end %>
  </span>
</nav>