config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
              controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end
  
  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: [:index] do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: :index
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: [:new, :create]
  before_action :find_question, only: [:show, :destroy, :edit, :update]

  rescue_from ActiveRecord::RecordNotFound, with: :record_question_not_found

  def show; end
  
  def new
    @question = @test.questions.build
  end

  def edit; end

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to admin_test_path(@question.test)
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @question.destroy

    redirect_to admin_test_path(@question.test)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end
  
  def question_params
    params.require(:question).permit(:body)
  end

  def record_question_not_found
    render plain: "Question Not Found"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header
    test_title = @question.test.title
    @question.new_record? ? "<#{test_title}>" : "<#{test_title}>"
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with(model: [:admin, @test, @question], local: true) do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </p><br>

  <%= form.submit %>
<% end %>

app/views/admin/questions/_question.html.erb
<p>
  <%= question.id %>.
  <%= question.body %>
<p>
<%= link_to t(".show"), admin_question_path(question) %>
<%= link_to t(".edit"), edit_admin_question_path(question) %>
<%= link_to t(".delete"), admin_question_path(question),
                  data: {
                    turbo_method: :delete,
                    turbo_confirm: t(".confirm")
                  } %>

app/views/admin/questions/edit.html.erb
<h3><%= t(".header", title: question_header) %> </h3>

<%= render 'form' %>

<p><%= link_to t(".back"), admin_test_path(@question.test) %></p>

app/views/admin/questions/new.html.erb
<h3><%= t(".header", title: question_header) %> </h3>

<%= render 'form' %>

<p><%= link_to t(".back"), admin_test_path(@test) %></p>

app/views/admin/questions/show.html.erb
<h3><%= t(".question_header") %>:</h3>

<p><%= @question.body %></p>

<h2><%= t(".answer_header") %></h2>

<%= link_to t(".new_answer"), new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<p><%= link_to t(".edit"), edit_admin_question_path(@question) %></p>
<p><%= link_to t(".delete"), admin_question_path(@question), data: {
                    turbo_method: :delete,
                    turbo_confirm: t(".confirm")
                  }  %></p>


<p><%= link_to t(".back"), admin_tests_path(@question.test) %></p>